version: '2.0'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'api-estudos'
      MYSQL_USER: 'api'
      MYSQL_PASSWORD: 'api'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - sample:/var/lib/mysql
volumes:
  sample:
